AWSTemplateFormatVersion: '2010-09-09'
Description: Just an ACM certificate.

Parameters:
  DomainName:
    Type: String
    Description: The domain name
  HostedZoneId:
    Type: String
    Description: HostedZoneId for the Domain

Resources:
  Certificate:
    Type: "AWS::CertificateManager::Certificate"
    Properties:
      CertificateTransparencyLoggingPreference: ENABLED
      DomainName: !Ref DomainName
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS

Outputs:
  CertificateArn:
    Value: !Ref Certificate
